apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prod1
  namespace: argocd
spec:
  project: argo2
  source:
    repoURL: https://github.com/yatishg17/argo2.git
    targetRevision: prod
    path: apps/nginx/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true