apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: staging-1
spec:
  template:
    spec:
      containers:
        - name: nginx
          image: ghcr.io/yatishg17/argo2/nginx:latest
  replicas: 1